# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6e8dee9fa4f72e825c98d129a1a8f40a3accc8b171c6357a052cfbdc8f019abbdffc0241980723e12627388019fe02dc859c6f3c2b55734c82b10d49acffa088

test:
  secret_key_base: ec5e941e8c232ab548e72313841fa61715dff6ab6635497bb90af8d8f30607bb21e26625a93bfb880c0726fdd3c9bee0d5e437e8ecb518ec86e6fdb499d8b03f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
